version: '3'
services:
  webserver:
    image: 1767526/flsk:v2
    ports:
      - "3000"
    restart: always
    network_mode: host
    volumes:
      - /home/docker/:/usr/share/nginx/html
  frontend:
    image: 1767526/frontend:v2
    ports:
      - "80"
    network_mode: host
    restart: always
